# Generated by Django 5.2.7 on 2025-10-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('coin', 'Coin'), ('rank', 'Rank')], max_length=20)),
                ('price', models.PositiveIntegerField(help_text='price in som (integer)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
